# Generated by Django 5.1.6 on 2025-03-01 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRANSACTION_LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.cart')),
            ],
        ),
    ]
