# Generated by Django 5.1.5 on 2025-01-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='itemQuantAdded',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='itemTotal',
        ),
    ]
