# Generated by Django 5.0.6 on 2025-01-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
